"""create readings table

Revision ID: 76ce9f34d9d8
Revises: 
Create Date: 2026-06-17 08:52:09.052769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ce9f34d9d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('tds', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('growth_days', sa.Integer(), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(length=64), nullable=False),
    sa.Column('actuator_command', sa.String(length=64), nullable=False),
    sa.Column('anomaly', sa.String(length=64), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_created_at'))

    op.drop_table('readings')
    # ### end Alembic commands ###
